### ISSUE TITLE
Only works in Windows 11

### ISSUE THREAD

**Issue by GreenSoupDeveloper** [SipaaKernel-Project/SiCode-IDE#1]
i found a error that i create a project, and it creates, but when i open the project in the program, sicode ide crashes, i found this error in 1.5 and 1.6

and the same error happen to me in Windows 10, Windows 7 and Windows 8.1

so i think it does work only in Windows 11 sadly
![Captura](https://user-images.githubusercontent.com/109924369/219688541-4b96506f-6ca0-403a-b322-5240b5e2af03.JPG)

**Comment by RaphMar2021** [comment]
This is a config bug
Please stop lying

**Comment by RaphMar2021** [comment]
It will be fixed in 1.6.1
